### ISSUE TITLE
사운드 설정을 적용하는방법의 수정이 필요합니다.

### ISSUE THREAD

**Issue by hololee** [dpdms529/PLAY_APP#70]
https://github.com/dpdms529/PLAY_APP/blob/cd5e54e21c210ab859e0fd33cd7dfd511b021eb8/app/src/main/java/com/example/play_app/HomeActivity.kt#L51

https://github.com/dpdms529/PLAY_APP/blob/cd5e54e21c210ab859e0fd33cd7dfd511b021eb8/app/src/main/java/com/example/play_app/HomeActivity.kt#L110

_다른 Activity의 instance 를 바로 참조 하려 하지 말고 버튼을 통해 변경한 SharedPreference 의 값을 참조해주세요._

**Comment by dpdms529** [comment]
수정완료했습니다
